Profile new
mbnexttime/health_app pull request #4
Opened 2022-04-15 17:38 UTC by MashaK5

2022-04-15 17:43 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/db/DB.kt
> +}
лишнее

2022-04-15 17:43 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/DebugFragment.kt
> +            return@FragmentHolder ProfileFragment()
добавь просто свой снизу, не нужно удалять тот что уже есть

2022-04-15 19:29 UTC, mbnexttime requested changes

2022-04-15 19:29 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/profile/ProfileFragment.kt
> +                    "мужской" -> sexMan.isChecked = true
магические константы

2022-04-15 19:29 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/profile/ProfileFragment.kt
> +                sexMan.text = "м"
может лучше иконками?

2022-04-15 19:29 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/profile/ProfileFragment.kt
> +                val currentAge = fieldAge.text.toString()
посмотри в сторону UserDataHolder, он уже есть в main ветке
бери age оттуда и складывай туда же

2022-05-13 19:40 UTC, MashaK5 commented
Некоторые исправления не делала, мы о них разговаривали и ты разрешил оставить как есть

2022-05-14 00:30 UTC, mbnexttime requested changes

2022-05-14 00:30 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/profile/ProfileFragment.kt
> +//        val uriImage = userDataHolder.getUserDataString(UserDataType.URI)
почему закоменчено?

2022-05-14 00:30 UTC, mbnexttime commented
все хорошо, но не понимаю почему фотка профиля под комментарием

2022-05-14 16:32 UTC, MashaK5 commented
Потому что вылетает с этой штукой почему-то

2022-05-15 07:15 UTC, merged