Testing parts
mbnexttime/health_app pull request #6
Opened 2022-04-15 17:48 UTC by Gor1x

2022-04-15 19:37 UTC, mbnexttime requested changes

2022-04-15 19:37 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                    viewBinding.reactionButton.text = "Wait for choice."
в ресурсы

2022-04-15 19:37 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/DebugFragment.kt
> +            return@FragmentHolder ComplexTestReactionFragment()
добавь свой рядом, не удаляй тот что есть

2022-04-15 19:37 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/BaseDebugFragment.kt
> +class BaseDebugFragment : Fragment(R.layout.activity_main)
?

2022-04-15 19:37 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                    //Toast.makeText(requireContext(), "$time", Toast.LENGTH_SHORT).show()
убрать

2022-04-15 19:37 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                    val time = (nextDouble(2.0, 4.0) * 1000).toLong()
магические константы

2022-04-15 19:37 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                else -> {}
assert

2022-04-15 19:37 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                    if (counter == 10) {
same

2022-04-15 19:37 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                    viewBinding.reactionButton.setBackgroundColor(resources.getColor(R.color.purple_700))
почему для зеленой такого нет?

2022-04-15 19:37 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +            viewBinding.reactionButton.text = "Something happens! Try again."
что здесь происходит?

2022-04-15 19:37 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/TestReactionFragment.kt
> +}
все то же самое, что и для предыдущего теста

2022-04-28 18:53 UTC, Gor1x commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                    val time = (nextDouble(2.0, 4.0) * 1000).toLong()
@AndreyYurko

2022-05-15 13:35 UTC, AndreyYurko commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +            viewBinding.reactionButton.text = "Something happens! Try again."
В случае если пользователь например выходит из приложения, но не убивает его, то надо это как-то обработать

2022-05-15 17:50 UTC, AndreyYurko commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                    viewBinding.reactionButton.text = "Wait for choice."
Добавил

2022-05-15 17:50 UTC, AndreyYurko commented on app/src/main/java/com/example/psyhealthapp/debug/DebugFragment.kt
> +            return@FragmentHolder ComplexTestReactionFragment()
Сделано

2022-05-15 17:50 UTC, AndreyYurko commented on app/src/main/java/com/example/psyhealthapp/debug/BaseDebugFragment.kt
> +class BaseDebugFragment : Fragment(R.layout.activity_main)
Просто тестировал, забыл удалить

2022-05-15 17:50 UTC, AndreyYurko commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                    //Toast.makeText(requireContext(), "$time", Toast.LENGTH_SHORT).show()
Убрано

2022-05-15 17:51 UTC, AndreyYurko commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                    val time = (nextDouble(2.0, 4.0) * 1000).toLong()
Заменил все кроме 1000, кол-во мс в секунде считаю не магической

2022-05-15 17:51 UTC, AndreyYurko commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                    if (counter == 10) {
На коунтер ассерт?

2022-05-15 17:52 UTC, AndreyYurko commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                    viewBinding.reactionButton.setBackgroundColor(resources.getColor(R.color.purple_700))
Потому что это надо было убрать

2022-05-15 17:52 UTC, AndreyYurko commented on app/src/main/java/com/example/psyhealthapp/debug/TestReactionFragment.kt
> +}
Сделано

2022-05-15 18:27 UTC, Gor1x commented on app/src/main/java/com/example/psyhealthapp/debug/ComplexTestReactionFragment.kt
> +                    val time = (nextDouble(2.0, 4.0) * 1000).toLong()
TimeUnit.SECONDS.toMilliseconds(seconds) возможно будет лучше, если оставлять 1000 то заводить константу, чтобы не приходилось думать над тем что это за число и какая это единица измерения

2022-05-23 03:23 UTC, mbnexttime approved these changes

2022-05-23 03:56 UTC, merged