Tapping test
mbnexttime/health_app pull request #7
Opened 2022-04-15 17:55 UTC by Gor1x

2022-04-15 19:40 UTC, mbnexttime requested changes

2022-04-15 19:40 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/DebugFragment.kt
> +                    .remove(localCurrentFragment).commit()
?

2022-04-15 19:40 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/user/testing/tappingtest/ui/TappingTestChallengeFragment.kt
> +        return inflater.inflate(R.layout.tapping_test_challenge_fragment, container, false)
можешь в конструктор фрагмента передать R.layout.tapping_test_challenge_fragment

2022-04-15 20:37 UTC, Gor1x commented on app/src/main/java/com/example/psyhealthapp/debug/DebugFragment.kt
> +                    .remove(localCurrentFragment).commit()
Слишком длинная строчечка, видимо студия подравняла. Могу убрать, но так читабельнее

2022-04-15 20:38 UTC, Gor1x commented on app/src/main/java/com/example/psyhealthapp/user/testing/tappingtest/ui/TappingTestChallengeFragment.kt
> +        return inflater.inflate(R.layout.tapping_test_challenge_fragment, container, false)
Что ты имеешь в виду? А почему такое не подойдет?

2022-04-15 20:46 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/user/testing/tappingtest/ui/TappingTestChallengeFragment.kt
> +        return inflater.inflate(R.layout.tapping_test_challenge_fragment, container, false)
потому что лучше в конструктор передать параметр, чем оверрайдить метод
Fragment(R.layout...)

2022-04-22 13:23 UTC, mbnexttime commented on app/src/main/java/com/example/psyhealthapp/debug/DebugFragment.kt
> +                    .remove(localCurrentFragment).commit()
убери

2022-04-29 15:18 UTC, merged